---
stages:
  - build
  - test
  - review

before_script:
  - export TAG=${CI_COMMIT_SHA}
  - export BRANCH=${CI_COMMIT_REF_NAME}
  - export REGISTRY_HOST=${CI_REGISTRY}
  - export REGISTRY_URI="/${CI_PROJECT_PATH}"

hyku.build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    refs:
      - merge_requests
  tags:
    - local

lint:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  allow_failure: true
  script:
    - bundle check || bundle
    - bundle exec rubocop
  only:
    refs:
      - merge_requests
  tags:
    - docker

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  allow_failure: true
  services:
    - name: bitnami/postgresql:12.6.0
      alias: db
    - name: samvera/fcrepo4:4.7.5
      alias: fcrepo
    - name: redis:5-alpine
      alias: redis
    - name: solr:8.7
      alias: solr
    - name: selenium/standalone-chrome:3.141
      alias: chrome
  script:
    - bundle exec rspec
  only:
    refs:
      - merge_requests
  tags:
    - docker

hyku.review:
  stage: review
  needs: ["hyku.build"]
  extends:
    - .deploy
  environment:
    name: hyku.review/$CI_MERGE_REQUEST_ID
    url: http://hyku-$CI_MERGE_REQUEST_ID.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: hyku.review.stop
    auto_stop_in: 1 day
  only:
    refs:
      - merge_requests
  variables:
    DEPLOY_IMAGE: $CI_REGISTRY_IMAGE
    DEPLOY_TAG: $CI_COMMIT_SHA
    HELM_EXPERIMENTAL_OCI: 1
    HELM_RELEASE_NAME: hyku-$CI_MERGE_REQUEST_ID
    KUBE_NAMESPACE: hyku-review
    HELM_EXTRA_ARGS: >
      --values review-deploys.yaml
      --set ingress.enabled=true
      --set ingress.hosts[0].host=hyku-$CI_MERGE_REQUEST_ID.$KUBE_INGRESS_BASE_DOMAIN
      --set ingress.hosts[0].paths={"/"}
  script:
    - helm registry login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - helm chart pull registry.gitlab.com/notch8/britishlibrary/hyrax:0.9.0
    - helm chart export registry.gitlab.com/notch8/britishlibrary/hyrax:0.9.0
    - deploy hyrax
  tags:
    - kubernetes

hyku.review.stop:
  stage: review
  extends:
    - .deploy
  environment:
    name: hyku.review/$CI_MERGE_REQUEST_ID
    url: http://hyku-$CI_MERGE_REQUEST_ID.$KUBE_INGRESS_BASE_DOMAIN
    action: stop
  when: manual
  allow_failure: true
  variables:
    HELM_RELEASE_NAME: hyku-$CI_MERGE_REQUEST_ID
    KUBE_NAMESPACE: hyku-review
    GIT_STRATEGY: none
  script:
    - delete
  tags:
    - kubernetes

.deploy_helpers: &deploy_helpers |
  function deploy() {
    helm repo update

    chart="${1}"

    helm upgrade \
        --kubeconfig $KUBECONFIG_BL \
        --install \
        --atomic \
        --timeout 15m0s \
        --set image.repository="$DEPLOY_IMAGE" \
        --set image.tag="$DEPLOY_TAG" \
        $HELM_EXTRA_ARGS \
        --namespace="$KUBE_NAMESPACE" \
        --create-namespace \
        "$HELM_RELEASE_NAME" \
        "${chart}"
  }

  function delete() {
    echo "Deleting release: $HELM_RELEASE_NAME..."
    helm delete --namespace "$KUBE_NAMESPACE" "$HELM_RELEASE_NAME"
  }

.deploy:
  image: dtzar/helm-kubectl:3.5.3
  before_script:
    - *deploy_helpers
