all:
  exclude:
    - 'spec/**/*'
    - 'views/**/*'
# exclude files for single runner
eslint:
  exclude:
    - 'app/assets/**/*'
gitlab:
  slug: 25227432 # gitlab's project ID
  api_private_token: 46751
  api_endpoint: https://gitlab.com/api/v4
