all:
  exclude:
    - 'spec/**/*'
    - 'views/**/*'
# exclude files for single runner
eslint:
  exclude:
    - 'app/assets/**/*'
gitlab:
  slug: 25227432 # gitlab's project ID
  api_private_token: PRONTO_GITLAB_API_PRIVATE_TOKEN
  api_endpoint: https://gitlab.com/api/v4