development:
  enabled: true
  enable_send_logger: false
  enable_send_investigations: true
  enable_send_requests: true
  irus_server_address: https://irus.jisc.ac.uk/counter/test/
  robots_file: irus_analytics_counter_robot_list.txt
  verbose_debug: false
  source_repository: bl.test
  named_servers: true
  bl.bl.test:
    source_repository: bl.bl.test

# NB staging currently uses the rails production enviroment
# So the config here for test will not get used. 
# Instead staging will use the production config below and 
# therefore (as the staging servers are not in that) will 
# send the default source_repository (iro.bl.uk) to the 
# production IRUS endpoint when triggered by *.bl-staging...
# This is not too terrible as requests will be rare and IRUS 
# will probably ignore them, however using the test rails.ENV 
# on staging might be more wise in generally?
test: 
  enabled: true
  enable_send_logger: false
  enable_send_investigations: true
  enable_send_requests: true
  irus_server_address: https://irus.jisc.ac.uk/counter/test/
  robots_file: irus_analytics_counter_robot_list.txt
  verbose_debug: false
  source_repository: bl-staging.notch8.cloud
  named_servers: true
  bl.bl-staging.notch8.cloud: 
    source_repository: bl.bl-staging.notch8.cloud
  britishmuseum.bl-staging.notch8.cloud:
    source_repository: britishmuseum.bl-staging.notch8.cloud
  kew.bl-staging.notch8.cloud:
    source_repository: kew.bl-staging.notch8.cloud
  nms.bl-staging.notch8.cloud:
    source_repository: nms.bl-staging.notch8.cloud
  mola.bl-staging.notch8.cloud:
    source_repository: mola.bl-staging.notch8.cloud

production:
  enabled: true
  enable_send_logger: false
  enable_send_investigations: true
  enable_send_requests: true
  irus_server_address: https://irus.jisc.ac.uk/counter/
  robots_file: irus_analytics_counter_robot_list.txt
  verbose_debug: true
  source_repository: iro.bl.uk
  named_servers: true
  bl.iro.bl.uk:
    source_repository: bl.iro.bl.uk
  britishmuseum.iro.bl.uk:
    source_repository: britishmuseum.iro.bl.uk
  kew.iro.bl.uk:
    source_repository: kew.iro.bl.uk
  nms.iro.bl.uk:
    source_repository: nms.iro.bl.uk
  mola.iro.bl.uk:
    source_repository: mola.iro.bl.uk
