# These settings can also be provided as environment variables, in the form, e.g.:
#    SETTINGS__ACTIVE_JOB_QUEUE__URL=http://...
#
# The mapping is described in `./config/initializers/config.rb`.
#
multitenancy:
  enabled: false
  default_host: # "%{tenant}.dev"
  admin_host:
  admin_only_tenant_creation: true
  root_host:

solr:
  url: "http://127.0.0.1:8983/solr/"
  configset: hyku
  configset_source_path: <%= File.join(Rails.root, 'solr', 'config') %>
  collection_options:
    async:
    auto_add_replicas:
    collection:
      config_name: hyku
    create_node_set:
    max_shards_per_node:
    num_shards: 1
    replication_factor:
    router:
      name:
      field:
    rule:
    shards:
    snitch:

active_job_queue:
  url:
