image:
    repository: ENC[AES256_GCM,data:CV8Ahm0yGs/qGJuynA0HjEGYtXJVztG6,iv:PKDgPXAHYehdXNTBJ1MDvNGlPLkBuZZyAc4bC7EEZko=,tag:/dWZ7nOUd8aCpY40Zk3JUA==,type:str]
    tag: ENC[AES256_GCM,data:hzXz4tVw,iv:4kYp0z6Sexd3gHcYvlER1UpND1wVKE8x2FLP/dzMzQc=,tag:PKOAqN+H5ouNMQmFpURhYQ==,type:str]
primary:
    persistence:
        enabled: ENC[AES256_GCM,data:FdoBvA==,iv:RQAvfglM+dI6ndeTYYItYdxAjc+k+Ypnu6HLUN1qjXU=,tag:ge5QZMk64SjM+3DEP/i9bg==,type:bool]
        size: ENC[AES256_GCM,data:N3wX0A==,iv:HfBh261qygA9vWJj7P0KMDcyHYHWuoUyRV+nqU0bHDE=,tag:rVZ0Q8qWIbhgRGwzraUdoA==,type:str]
        storageClass: ENC[AES256_GCM,data:+rma,iv:6ZYfXl7UMS5XS3tjdHM5ylGgoigv6gSXqMNhNO2JBM0=,tag:1RLUAMnm/jjNxKP6jnxvEQ==,type:str]
readReplicas:
    persistence:
        enabled: ENC[AES256_GCM,data:DWzQ0g==,iv:r+vNgz4rAPabKTrxeNYfYrM+kJVFqixLqahuI9qZ5VY=,tag:4ctKQ25DEdU8QZiKlwdPkA==,type:bool]
        size: ENC[AES256_GCM,data:Ukrs5w==,iv:6glRsn6TllYtuWj+Lm0DcX3sYPmgXelbUtX/Cnge4oY=,tag:vewD4alk3hRMp3v2YCLiYA==,type:str]
        storageClass: ENC[AES256_GCM,data:hUUY,iv:zQNznTO/5fin5H1HrHzjkBBAo4fXEEjyM2OO66y5bQM=,tag:h88RGgVhB6PxN1/u0ty4Pw==,type:str]
auth:
    username: ENC[AES256_GCM,data:kVAu4Nxu,iv:cLV02JQ0x3JxxloczWRsCYLgZD4vNCjfGiVAcFBPdSM=,tag:bUMucUbUQl2gwDL8oh2ZsA==,type:str]
    password: ENC[AES256_GCM,data:q0dfeXyNjXt8Z01H7jTB6FWU,iv:aFwj3p8NPxISiWwfrygNlOPpdb8cnQT7C7N67OJEavQ=,tag:LMFGeNe+ZX6PwOgMo0Lfxg==,type:str]
    database: ENC[AES256_GCM,data:eBGZAb4+,iv:plJk4GnnrN1bBvDBC+hkF5oT7IA+xf+ptm3Q8ei6m/k=,tag:HQ6duHMzmxm/5Obb7mXt8Q==,type:str]
    replicationPassword: ENC[AES256_GCM,data:v8t31H4O/1sM8WP4znvzNOWIPqA=,iv:vPo2Lkzfj5zkEjLAbmezyGRFnjntWxBz/pck+HbVSGk=,tag:TqNz8RhVQSSz9F5wZvt2fA==,type:str]
metrics:
    enabled: ENC[AES256_GCM,data:cPwjLQ==,iv:+DlmJ58ym5uxdx1f46bNumftoS//W7qXrIuWAI6/Dpw=,tag:TCjW6XOxsAzkOa0WiHQZ6A==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-19T21:15:04Z"
    mac: ENC[AES256_GCM,data:chdVgI0oC4wzJujvDGD7IW4AGBU6qIBf1F8XRBZWJZquh6Hsv11twV2IFCXkP03gbgnyaKkCqVGUK27YqPQQh6ua6Q5vytbcVIUYEfIbLIE+165hiRfCWjOM92MyiHPSI+6Rq/GlCq/TzlcUdnb1MlHykxe7XQROTEK69uObvXI=,iv:w27bdERHsktSA/uEVhmml1iJZKPGpdAq2Iz8NUWGWnM=,tag:cpJY/bNqJ2Y5LnrCLL9+3w==,type:str]
    pgp:
        - created_at: "2025-11-19T21:15:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7doaBdjNJH+AQ//R+EJyv7LPI/6cQx0KQfsJoQtm5J/NdAhJe/2ghBzMTTG
            3kgeD1lU8IdBokBeCNOnEGpmkEyNsWFeSTnu2sQ4w7I/0aBy+5zOIUE3Dzw8fC7s
            20iwrwsGLhq7+ZSVMh4W4wtmZGyTaHcmP0wiyW0b5gz+LjB/g72lyXqtLSm1trTQ
            6tzrPUH5wr1k5hMvFglP1gwxx6LLSudhL0q6VCyIl3kJbEYjIfY1734Cst6iIEQM
            IcqiBEfXDs+R9i6eXjkcWec4ehrhNIp2VmysGqQxNKjUZVFTMczLOBqboa2goZwq
            AHOIAqoMy+fp2wCppW4pE2Nz/tWpFY5uZcvTcMsa+vt5ZE4fZlLJgsDuPvZv4lyZ
            oIUy4QaOKgVNGw39xI4adTDz2M7RvSUcjEReXp0wCjfdkGEDmhE946JMg+DUIrb8
            GIE+L1CWioSPf6r7fitqlJ4UTJuUdszkjgPQsvP4G10yuiZfO2vInLpJtRfu0Rvc
            waz8jwk8U11Dk83wtFKoyKqNHSTXRLYn36cFhx9sX/1+gwNYJc0nU3RdUT85ld8F
            A5i9Vo+ZVZ+RF9eZAJCS8Qc1bgVKzEAJKz/N4iPFhMAnZzRWnYMW9qK6Qg/5H+4C
            bwwL4TnLNqZmHUGNylHqFhLsdIKChVJTyZnDSxB4/0veMIigfwe0v4YMeMn/DGzS
            XAFcZI2fXbnU7RnCv3n1inf81xyq8dL5TA+GuaAwsyo/u2Pk94xsai+RF9gIEznN
            0lf4MdOVmgPVIJ7usFBGo53tUyDuGhW0VjR6nx7LWpK0RJY0DePb12fZG6tX
            =rdjy
            -----END PGP MESSAGE-----
          fp: 40B3DE7A02CAC8D1DE76223483DA3B754DD29AF9
    unencrypted_suffix: _unencrypted
    version: 3.8.1
