#ENC[AES256_GCM,data:gFt1Ll+ecOGPq1qd,iv:mmjDKs0XAvdRTFftrwr2NhRI1fq/BuWzvTOYufSqaKg=,tag:+IHfHgNljpCulAgkuj/bhg==,type:comment]
global:
    security:
        allowInsecureImages: ENC[AES256_GCM,data:buxRxw==,iv:RT4Sq7wIi28AY0N/bDA0jKY6yBTgvoZUEi8tvIv5fE0=,tag:T809tob9DB5Poi6QMRyYdw==,type:bool]
image:
    repository: ENC[AES256_GCM,data:rPsYPLH2jhd6A27goSTkuTYr,iv:iLXy+S0jSJnRUgTHG4S2aFamGHcVCbpOoeNEnRagGUk=,tag:7JwRYJpGbnqiTYlzeMq1IQ==,type:str]
    tag: ENC[AES256_GCM,data:iATp78xoy0Ek3M8LLtXBPAqTQg==,iv:XafhSkD2bolrd86pV5p1d4kUnKA4fbZLzc0G0n3yfkM=,tag:UaGuxwdggt3ZmJ3YSWZ6Mw==,type:str]
replicaCount: ENC[AES256_GCM,data:Sg==,iv:hBPnEr5hmo9WDzeuyZuuByKAP8f/AI/47D60RZVbxNE=,tag:g3N+7misLA0+3Z1S3hLTHA==,type:int]
collectionReplicas: ENC[AES256_GCM,data:GQ==,iv:cTdP+FZuF3KKJaBz4EyfmOxHyYh+Z2VNYcaotAThQb0=,tag:oH9xx8k4vg4yNylmE4NQvA==,type:int]
authentication:
    enabled: ENC[AES256_GCM,data:QNYh5Q==,iv:eYg8ebEWX7SDd4izl/bXxHDqmN0NTnyEBBC+4zfVCdg=,tag:z6x+t2gn63oxfsY7AE9e5A==,type:bool]
    adminUsername: ENC[AES256_GCM,data:Q1KwxDA=,iv:sA94gBi+viLnkIYss07i/K7bm5u9HzFEIRfbufpSgsY=,tag:oq8o7/9w2/VVaPVl7DJDUA==,type:str]
    adminPassword: ENC[AES256_GCM,data:HN/gbiA=,iv:Wg/L/cC7kgMX/S0/r8AvRcNCWSFMdKh4OK9LZy+5neA=,tag:S2LnYpqUz8N1SXG7mPEpmg==,type:str]
javaMem: ENC[AES256_GCM,data:1ynjOIM7YAlzfyvnDA==,iv:Bmx1BL5YuljH4VqwhJMUAvOJ7J6Jfqc0/MczHuC7wN8=,tag:jH/cA+rXMIg4ahApLuRnzA==,type:str]
resources:
    limits:
        memory: ENC[AES256_GCM,data:Nhtk,iv:axUFZaHiFwN6Cm5AEAQfddvRsaN9DC9pIzpamWUnfLw=,tag:tFI+Vcy59d+uVW6zQJI3/g==,type:str]
    requests:
        memory: ENC[AES256_GCM,data:yVR9,iv:IGgbkTULSmgJeoKsn6Qb0eJwKLjuIkWhEzKVBJNeZbs=,tag:nRfETxs7haV5sk07gJA5cQ==,type:str]
zookeeper:
    image:
        repository: ENC[AES256_GCM,data:XlgmX/Itl7sfBQzl/cPnyGvL56Gg0rg=,iv:H7VQcpYr/vfwRAsGH+thT4pERHGudp+ZngkpcFYL77E=,tag:cDBG1fVz7xfC6v+eIjuvGQ==,type:str]
        tag: ENC[AES256_GCM,data:uXEiktg=,iv:3W5p2/sFaKFL4gbpcJPaO51L5VDnYV1MdlFFzRLVaqE=,tag:T9bqBz8c4Z+QFqLSiIVx6Q==,type:str]
    replicaCount: ENC[AES256_GCM,data:ng==,iv:xMAXt6ya/11pOO8ctS6Uxyj7/AWo9BabCDXb+99xPLo=,tag:t/x3uZ55IXUEnpRi2y7teg==,type:int]
    env:
        JVMFLAGS: ENC[AES256_GCM,data:Q7CgH+c3CwGG7a1GR5gd,iv:VQuN/vWtjL2rn2Sc7ozqABnMLNLEhrAmSS2TyAVB5AM=,tag:XERzTVJvEh7NZItFb4fAmQ==,type:str]
    resources:
        limits:
            memory: ENC[AES256_GCM,data:VGA7,iv:ghUdjiPMkUDIlQZ23mbT4TYZ5t3y+W2xbuBCNwFGfRE=,tag:0pvtHxbMxXeuTS0SoLEpig==,type:str]
        requests:
            memory: ENC[AES256_GCM,data:xrPkafE=,iv:vUjBLgTjugMn1m210kDA71SwlC4YoejyQ0BJyWt2lec=,tag:P5bFcH/O9Xfrwc5/BoTAzA==,type:str]
persistence:
    enabled: ENC[AES256_GCM,data:+MOwQQ==,iv:1u6+MUb/gl4s5cMarSO4pfBa6MO3+4X1nOQt4i/cLmU=,tag:LvbYpzfO3V6h5XZhAb18Kw==,type:bool]
    storageClass: ENC[AES256_GCM,data:VrVg,iv:ObOwbhi21y+HSwoO0s0UC9z1UGgmr0F2pGctv1hACdY=,tag:X1a8TvsmS9drO5PPqEHwtg==,type:str]
    size: ENC[AES256_GCM,data:3NVkwp4=,iv:ls0n9wXL7ofNV38VPp4BYqzSpsx68QP9ijgVaaFlyAY=,tag:hq+4iGUdKTVgeE/LlutWKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-19T21:30:36Z"
    mac: ENC[AES256_GCM,data:OSm7376YSQLFh0v6XvsU6mLEKwmBv91B2uC5BPoO4O526oNpIXVFgT3ctCgWOq1IPq3kUFivV3haayvxgfRZXVZeIYZjIhTbagMMVA6QS6jjNPpwznVzWdhPOHcHL7tB61LoNey1hQtPpDXqjtG+6WRBREU559neaYN4kGZkwwA=,iv:tLvLgQzD9aDwKpDQsDCY/lXigspYN+M+cuarDg+FrnU=,tag:OvNBGxDtDVwck9bQBxdrQg==,type:str]
    pgp:
        - created_at: "2025-11-19T21:30:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7doaBdjNJH+AQ/5AY5lf1KkVDPuQDGYeHHbcWmIpcvufgWgq11NmzYyN93a
            Wglp6wh4vZY9TSGB1YVQk++pnA1XgAPMBWnlkBwmsD3SyRR8R14WESL/8kiFsTMW
            l7O1MiEQ9ZsWtV/GPjWZZLXxlKvxLgjPOWxaAY1noSRiUXRrEYvy7jgx4K4fWKq0
            Y559xXh1qzCu8A1sAGzRSB197MYCzEBl+UY/mVnlMq0onSgXYCO6bdAwDnuvktBK
            QU1vI9qBfsJZW82kpHdxLpQxikbDYLqNTmCJzU6XTuA82N8KxY4rvigXU7YbQOHl
            zv2GLxWO1hFqGQF5MuDlWFY2upooGrYelE5REehkzF4HiLY4fkrSeH0vunaBpdF5
            12+HPVdFZpqqlH0h4B8EdbzzkyilJCjDa/pblvpICwgekYM9XoZmvNTflCpu3NGP
            bRGI5H/KQjnSUcWleMwf0JtCdDp+UJAYkZEc7JWybit+QeslX0VyJKtNhRN5i440
            1DeaxYz03rm3Q4F8iyDxahPZXphIhdrI1h87fC8wAcUZ/rO7aoaR3TfTmWYAW/fg
            YzeWeHF/CcAqa3Q+2jvn2jcMQgSPq9P8cGUfsBmzKv7g3c+DktTA8XimGs1F7grW
            j5d8KBKxnCKYCG9nUqtX7s50rqRHry6h7wsGQBFecLSa8JoDtf9WwMf6BljIg0HS
            XgEQazUi10PO4YvvyhPUNq2CxFslV6LQBMkWZ8qUbyqjEoAEHzwMcpv6gAZ4ZUE+
            t9Izw0gGKy0YivpKTPpshyqw7h7yaQQfhpzAPmnVtLQCzEnnITgN5fENi84ZbTI=
            =mVlA
            -----END PGP MESSAGE-----
          fp: 40B3DE7A02CAC8D1DE76223483DA3B754DD29AF9
    unencrypted_suffix: _unencrypted
    version: 3.8.1
