replicaCount: 2

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: efs-sc
derivativesVolume:
  storageClass: efs-sc
uploadsVolume:
  storageClass: efs-sc
  size: 200Gi

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files

ingress:
  enabled: true
  hosts:
    - host: oar.notch8.cloud
      paths:
        - path: /
    - host: "*.oar.notch8.cloud"
      paths:
        - path: /
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0",
    cert-manager.io/cluster-issuer: letsencrypt-production-dns
  }
  tls:
    - hosts:
        - oar.notch8.cloud
        - "*.oar.notch8.cloud"
      secretName: notch8cloud

extraEnvVars: &envVars
  - name: CONFDIR
    value: "/app/samvera/hyrax-webapp/solr/config"
  - name: DATABASE_ADAPTER
    value: postgresql
  - name: DATABASE_HOST
    value: postgresql.default.svc.cluster.local
  - name: DATABASE_NAME
    value: hyku
  - name: DATABASE_PASSWORD
    value: $PROD_DATABASE_PASSWORD
  - name: DATABASE_USER
    value: postgres
  - name: FCREPO_BASE_PATH
    value: /bl
  - name: FCREPO_HOST
    value: fcrepo.default.svc.cluster.local:8080
  - name: FCREPO_PATH
    value: /rest
  - name: FEDORA_URL
    value: http://fcrepo.default.svc.cluster.local:8080/rest
  - name: INITIAL_ADMIN_EMAIL
    value: support@notch8.com
  - name: INITIAL_ADMIN_PASSWORD
    value: testing123
  - name: IN_DOCKER
    value: "true"
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_CACHE_STORE_URL
    value: redis://:production@hyku-production-redis-master:6379/bl
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_MAX_THREADS
    value: "5"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: REDIS_HOST
    value: hyku-production-redis-master
  - name: REDIS_URL
    value: redis://:production@hyku-production-redis-master:6379/bl
  - name: HYRAX_ACTIVE_JOB_QUEUE
    value: sidekiq
  - name: HYKU_BULKRAX_ENABLED
    value: "true"
  - name: HYKU_CONTACT_EMAIL
    value: support@notch8.com
  - name: HYKU_FILE_ACL
    value: "false"
  - name: HYRAX_FITS_PATH
    value: /app/fits/fits.sh
  - name: HYKU_ADMIN_HOST
    value: iro.bl.uk
  - name: HYKU_ADMIN_ONLY_TENANT_CREATION
    value: "true"
  - name: HYKU_ALLOW_SIGNUP
    value: "false"
  - name: HYKU_DEFAULT_HOST
    value: "%{tenant}.iro.bl.uk"
  - name: HYKU_MULTITENANT
    value: "true"
  - name: HYKU_ROOT_HOST
    value: iro.bl.uk
  - name: HYKU_SMTP_SETTINGS
    value: '{"from":"openaccess@bl.uk","user_name":"apikey","password":"***REMOVED***","address":"smtp.sendgrid.net","domain":"bl.uk","port":"587","authentication":"plain","enable_starttls_auto":true}'
  - name: SMTP_ADDRESS
    value: smtp.sendgrid.net
  - name: SMTP_DOMAIN
    value: "bl.uk"
  - name: SMTP_ENABLED
    value: "true"
  - name: SMTP_PASSWORD
    value: "***REMOVED***"
  - name: SMTP_PORT
    value: "587"
  - name: SMTP_USER_NAME
    value: apikey
  - name: SMTP_TYPE
    value: plain
  - name: SOLR_ADMIN_USER
    value: admin
  - name: SOLR_COLLECTION_NAME
    value: hyku
  - name: SOLR_CONFIGSET_NAME
    value: hyku
  - name: SOLR_HOST
    value: solr.default.svc.cluster.local
  - name: SOLR_PORT
    value: "8983"
  - name: SOLR_URL
    value: http://admin:$PROD_SOLR_PASSWORD@solr.default.svc.cluster.local:8983/solr/
  - name: SECRET_KEY_BASE
    value: 2b989efef38672467771269e8e430afebf55faf20da72e302e1893a3a5de22d9967b30b18d4ef369c9d34a6ca7315f99cb13fb98825aea4ee347a21be70f917e

worker:
  replicaCount: 1
  extraVolumeMounts: *volMounts
  extraEnvVars: *envVars
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 101
    fsGroup: 101
    fsGroupChangePolicy: "OnRootMismatch"
podSecurityContext:
  runAsUser: 1001
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: "OnRootMismatch"

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

redis:
  cluster:
    enabled: true
  password: production

imagePullSecrets:
  - name: gitlab-registry

solr:
  enabled: false
  replicaCount: 2
  collectionReplicas: 1
  zookeeper:
    replicaCount: 1

fcrepo:
  enabled: false
  storage:
    size: 105Gi

postgresql:
  enabled: false

externalSolrHost: solr.default.svc.cluster.local
externalSolrUser: admin
externalSolrPassword: $PROD_SOLR_PASSWORD
externalSolrCollection: "hyku"
externalFcrepoHost: fcrepo.default.svc.cluster.local
externalPostgresql:
  username: postgres
  password: $PROD_DATABASE_PASSWORD
  database: hyku
  host: postgresql.default.svc.cluster.local
