name: "Build Base"
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: notch8/actions/.github/workflows/build.yaml@british-library
    secrets: inherit
    with:
      platforms: "linux/amd64"
      target: hyku-base
      