name: "Build Test Lint"
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: notch8/actions/.github/workflows/build.yaml@british-library
    secrets: inherit
    with:
      platforms: "linux/amd64"
      webTarget: hyku-base
      solrTarget: hyku-solr
      workerTarget: hyku-worker
  test:
    needs: build
    uses: notch8/actions/.github/workflows/test.yaml@british-library
  lint:
    needs: build
    uses: notch8/actions/.github/workflows/lint.yaml@british-library
    with:
      rubocop_cmd: 'bundle exec rubocop --parallel --format progress'
