name: "Deploy"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to Environment'
        require: true
        default: 'staging'
        type: choice
        options:
          - staging
          - demo
          - production
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

env:
  REGISTRY: ghcr.io

jobs:
  deployment:
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:3.9.4
    environment: ${{ inputs.environment }}
    env:
      HELM_EXPERIMENTAL_OCI: 1
      HELM_RELEASE_NAME: ${{ inputs.environment }}
      KUBE_NAMESPACE: ${{ inputs.environment }}
      HELM_EXTRA_ARGS: >
        --values ops/${{ inputs.environment }}-deploy.yaml
      KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
      KUBECONFIG: ./kubeconfig.yml
      SOLR_ADMIN_PASSWORD: ${{ secrets.SOLR_ADMIN_PASSWORD }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@v3plus5
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: Do deploy
        run: |
          echo $KUBECONFIG_FILE | base64 -d > $KUBECONFIG;
          DOLLAR=$ envsubst < ops/${{ inputs.environment }}-deploy.tmpl.yaml > ops/${{ inputs.environment }}-deploy.yaml;
          export DEPLOY_TAG=${TAG};
          export DEPLOY_IMAGE=ghcr.io/${REPO_LOWER};
          export WORKER_IMAGE=ghcr.io/${REPO_LOWER}/worker;
          ./bin/helm_deploy hyku-${{ inputs.environment }} ${{ inputs.environment }}
