name: "Deploy"
run-name: Deploy (${{ github.ref_name }} -> ${{ inputs.environment }}) by @${{ github.actor }} with SHA ${{ github.sha}}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to Environment'
        require: true
        default: 'staging'
        type: choice
        options:
          - staging
          - demo
          - production
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  call-workflow:
    uses: notch8/actions/.github/workflows/deploy.yaml@british-library
    with:
      k8s-release-name: hyku-${{ inputs.environment }}
      k8s-namespace: ${{ inputs.environment }}
    secrets: inherit